name: 'Initia Create a Release'
description: 'Create a release for a tag in your repository'
author: 'GitHub, Initia Labs'
inputs:
  tag_name:
    description: 'name of the tag for this release'
    required: true
  release_name:
    description: 'name of the release'
    required: true
  body:
    description: 'text describing the contents of the release. Not required if using `body_path`'
    required: false
  body_path:
    description: 'path to a file describing the contents of the release. Not required if using `body`'
    required: false
  draft:
    description: 'set to `true` to create a draft (unpublished) release; defaults to `false`'
    required: false
    default: 'false'
  prerelease:
    description: 'set to `true` for a prerelease. `false` for a full release; defaults to `false`'
    required: false
    default: 'false'
  commitish:
    description: 'the branch or commit SHA the git tag is created from. Unused if the git tag already exists; defaults to the SHA of the current commit'
    required: false
  owner:
    description: 'the repository owner's username, used for identifying the repository when releasing for external repositories; defaults to the current owner'
    required: false
  repo:
    description: 'the repository name, used for identifying the repository when releasing for external repositories; defaults to the current repository'
    required: false
outputs:
  id:
    description: 'the release ID'
  html_url:
    description: 'URL to view the release'
  upload_url:
    description: 'URL for uploading assets to the release'
runs:
  using: 'node20'
  main: 'dist/index.js'
